align_struct_field = true
always_for_in = true
always_use_return = false
annotate_untyped_fields_with_any = false
join_lines_based_on_source = true
margin=1500
remove_trailing_comma = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
align_assignment = true
align_conditional = true
#align_matrix = false
align_pair_arrow = true
conditional_to_if = true
format_docstrings = true
#import_to_using = false
normalize_line_endings = "auto"
#pipe_to_function_call = false
remove_extra_newlines = true
#short_to_long_function_def = false
#whitespace_typedefs = false
